# Specifies the version of the Compose file format.
version: '3'
# This header is meant for all of the containers that will be running
services:
#This is for the redis database
  db:
    container_name: tictacdb
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always

  web:
    container_name: tictacserver
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:3
    depends_on:
      db:
        condition: service_healthy
        restart: true     
    ports:
      - 3000:3000